version: '3.8' 
services: 
  app:
    build: .
    container_name: dict-app
    ports:
      - "5000:5000" 
    volumes:
      - .:/app 
      - dictionary_data:/app/data
    networks:
      - dictionary-network

volumes:
  dictionary_data:

networks:
  dictionary-network:
    driver: bridge


