apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dictionary-replica
  namespace: dict-pod
  labels:
    app: myapp
    tier: frontend
spec:
  replicas: 3  # modify the replicas according to your case
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: dict-app-replica
        image: vibhutijain12/dictionary-app  # Corrected indentation here
        ports:
        - containerPort: 5000

